version: "3.9"
services:
  ui-service-frontend:
    build: hotel-controller-demo/hotel-controller-UI
    ports:
      - 3000:3000
  ui-service-backend:
    build: hotel-controller-demo/express-postgres
    ports:
      - 3001:3001
    environment:
      PORT: 5432
      USER: "postgres"
      PASSWORD: 123
      DATABASE: "testdb"
      HOST: "db"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  spring-producer:
    build: spring-rabbitmq-producer
    ports:
      - 8080:8080
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
  spring-consumer:
    build: spring-rabbitmq-consumer
    ports:
      - 8081:8081
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
  db:
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
