name: Data Generator

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          if [ -f ./gpdb/data/requirements.txt ]; then pip install -r ./gpdb/data/requirements.txt; fi
      - name: Lint with black
        run: |
          black . --check --verbose
      - name: Test Generate Data
        run: |
          python3 ./gpdb/data/data-generator.py --csv tmp.csv
          (test -f tmp.csv && echo Generated file exists) || exit 1
