name: RabbitMQ

on:
  push:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: |
          cd rabbitmq && docker-compose -f "docker-compose.yml" up -d --build
